git clone git@github.com:sittercity/sittercity.git
git clone git@github.com:sittercity/empire.git
git clone git@github.com:sittercity/empire-admin.git
git clone git@github.com:sittercity/empire-utilities.git
git clone git@github.com:sittercity/sso-api.git
git clone git@github.com:sittercity/sso-admin.git
git clone git@github.com:sittercity/sso-client-gem.git
git clone git@github.com:sittercity/stormtrooper.git
git clone git@github.com:sittercity/empire-elasticsearch-query.git
git clone git@github.com:sittercity/vim_files.git
